type Semester = {
  _id: number;
  semesterId: string;
  semester: string;
  createdAt: string;
  updatedAtD: string;
};

type Course = {
  _id: number;
  semesterId: string;
  course_code: string;
  course_subject: string;
  course_teacher: string;
  course_grade: string;
  course_credits: string;
  course_type: string;
  course_amount: number;
};

export const registrationHistory: {
  semester: Semester[];
  semesterHistory: Record<string, Course[]>;
} = {
  semester: [
    {
      _id: 1,
      semesterId: "fall2026",
      semester: "Fall 2026",
      createdAt: "2026-05-02",
      updatedAtD: "2026-05-02",
    },
    {
      _id: 2,
      semesterId: "spring2026",
      semester: "Spring 2026",
      createdAt: "2026-05-02",
      updatedAtD: "2026-05-02",
    },
    {
      _id: 3,
      semesterId: "summer2026",
      semester: "Summer 2026",
      createdAt: "2026-05-02",
      updatedAtD: "2026-05-02",
    },
    {
      _id: 4,
      semesterId: "winter2026",
      semester: "Winter 2026",
      createdAt: "2026-05-02",
      updatedAtD: "2026-05-02",
    },
    {
      _id: 5,
      semesterId: "rainy2026",
      semester: "Rainy 2026",
      createdAt: "2026-05-02",
      updatedAtD: "2026-05-02",
    },
  ],

  semesterHistory: {
    fall2026: [
      {
        _id: 1,
        semesterId: "fall2026",
        course_code: "CSE101",
        course_subject: "Introduction to Programming",
        course_teacher: "Md Rahim Uddin",
        course_grade: "A",
        course_credits: "3",
        course_type: "Regular",
        course_amount: 12000,
      },
      {
        _id: 2,
        semesterId: "fall2026",
        course_code: "MAT101",
        course_subject: "Mathematics I",
        course_teacher: "Md Karim",
        course_grade: "A+",
        course_credits: "3",
        course_type: "Regular",
        course_amount: 10000,
      },
      {
        _id: 3,
        semesterId: "fall2026",
        course_code: "ENG101",
        course_subject: "English I",
        course_teacher: "Ms Shila",
        course_grade: "A-",
        course_credits: "2",
        course_type: "Regular",
        course_amount: 8000,
      },
      {
        _id: 4,
        semesterId: "fall2026",
        course_code: "PHY101",
        course_subject: "Physics",
        course_teacher: "Mr Hasan",
        course_grade: "B+",
        course_credits: "3",
        course_type: "Regular",
        course_amount: 11000,
      },
      {
        _id: 5,
        semesterId: "fall2026",
        course_code: "CHE101",
        course_subject: "Chemistry",
        course_teacher: "Mr Amin",
        course_grade: "A",
        course_credits: "3",
        course_type: "Regular",
        course_amount: 11000,
      },
    ],

    spring2026: [
      {
        _id: 6,
        semesterId: "spring2026",
        course_code: "CSE201",
        course_subject: "Data Structures",
        course_teacher: "Md Moniruzzam Khan",
        course_grade: "A+",
        course_credits: "3",
        course_type: "Regular",
        course_amount: 15000,
      },
      {
        _id: 7,
        semesterId: "spring2026",
        course_code: "MAT201",
        course_subject: "Mathematics II",
        course_teacher: "Mr Rahman",
        course_grade: "A",
        course_credits: "3",
        course_type: "Regular",
        course_amount: 12000,
      },
      {
        _id: 8,
        semesterId: "spring2026",
        course_code: "ENG201",
        course_subject: "English II",
        course_teacher: "Ms Shila",
        course_grade: "A-",
        course_credits: "2",
        course_type: "Regular",
        course_amount: 9000,
      },
      {
        _id: 9,
        semesterId: "spring2026",
        course_code: "STA201",
        course_subject: "Statistics",
        course_teacher: "Mr Karim",
        course_grade: "B+",
        course_credits: "3",
        course_type: "Regular",
        course_amount: 11000,
      },
      {
        _id: 10,
        semesterId: "spring2026",
        course_code: "ECO201",
        course_subject: "Economics",
        course_teacher: "Mr Hasan",
        course_grade: "A",
        course_credits: "3",
        course_type: "Regular",
        course_amount: 10000,
      },
    ],

    summer2026: [
      {
        _id: 11,
        semesterId: "summer2026",
        course_code: "CSE301",
        course_subject: "Algorithms",
        course_teacher: "Mr Tanvir",
        course_grade: "A",
        course_credits: "3",
        course_type: "Regular",
        course_amount: 15000,
      },
      {
        _id: 12,
        semesterId: "summer2026",
        course_code: "DBMS301",
        course_subject: "Database",
        course_teacher: "Mr Rakib",
        course_grade: "A+",
        course_credits: "3",
        course_type: "Regular",
        course_amount: 14000,
      },
      {
        _id: 13,
        semesterId: "summer2026",
        course_code: "SE301",
        course_subject: "Software Engineering",
        course_teacher: "Ms Lima",
        course_grade: "A-",
        course_credits: "3",
        course_type: "Regular",
        course_amount: 13000,
      },
      {
        _id: 14,
        semesterId: "summer2026",
        course_code: "AI301",
        course_subject: "AI Basics",
        course_teacher: "Mr Arif",
        course_grade: "B+",
        course_credits: "3",
        course_type: "Regular",
        course_amount: 15000,
      },
      {
        _id: 15,
        semesterId: "summer2026",
        course_code: "NET301",
        course_subject: "Networking",
        course_teacher: "Mr Hasan",
        course_grade: "A",
        course_credits: "3",
        course_type: "Regular",
        course_amount: 14000,
      },
    ],

    winter2026: [
      {
        _id: 16,
        semesterId: "winter2026",
        course_code: "CSE401",
        course_subject: "Compiler",
        course_teacher: "Mr Jewel",
        course_grade: "A",
        course_credits: "3",
        course_type: "Regular",
        course_amount: 16000,
      },
      {
        _id: 17,
        semesterId: "winter2026",
        course_code: "SEC401",
        course_subject: "Cyber Security",
        course_teacher: "Mr Arif",
        course_grade: "A+",
        course_credits: "3",
        course_type: "Regular",
        course_amount: 17000,
      },
      {
        _id: 18,
        semesterId: "winter2026",
        course_code: "ML401",
        course_subject: "Machine Learning",
        course_teacher: "Mr Tanvir",
        course_grade: "A-",
        course_credits: "3",
        course_type: "Regular",
        course_amount: 18000,
      },
      {
        _id: 19,
        semesterId: "winter2026",
        course_code: "DS401",
        course_subject: "Distributed Systems",
        course_teacher: "Mr Rakib",
        course_grade: "B+",
        course_credits: "3",
        course_type: "Regular",
        course_amount: 15000,
      },
      {
        _id: 20,
        semesterId: "winter2026",
        course_code: "CLOUD401",
        course_subject: "Cloud Computing",
        course_teacher: "Ms Lima",
        course_grade: "A",
        course_credits: "3",
        course_type: "Regular",
        course_amount: 16000,
      },
    ],

    rainy2026: [
      {
        _id: 21,
        semesterId: "rainy2026",
        course_code: "CSE501",
        course_subject: "Advanced React",
        course_teacher: "Mr Hasan",
        course_grade: "A+",
        course_credits: "3",
        course_type: "Regular",
        course_amount: 20000,
      },
      {
        _id: 22,
        semesterId: "rainy2026",
        course_code: "NODE501",
        course_subject: "Node.js Backend",
        course_teacher: "Mr Rahim",
        course_grade: "A",
        course_credits: "3",
        course_type: "Regular",
        course_amount: 18000,
      },
      {
        _id: 23,
        semesterId: "rainy2026",
        course_code: "DEVOPS501",
        course_subject: "DevOps",
        course_teacher: "Mr Karim",
        course_grade: "A-",
        course_credits: "3",
        course_type: "Regular",
        course_amount: 17000,
      },
      {
        _id: 24,
        semesterId: "rainy2026",
        course_code: "UI501",
        course_subject: "UI/UX Design",
        course_teacher: "Ms Shila",
        course_grade: "B+",
        course_credits: "2",
        course_type: "Regular",
        course_amount: 12000,
      },
      {
        _id: 25,
        semesterId: "rainy2026",
        course_code: "PROJECT501",
        course_subject: "Final Project",
        course_teacher: "Mr Moniruzzam",
        course_grade: "A",
        course_credits: "4",
        course_type: "Project",
        course_amount: 25000,
      },
    ],
  },
};