export const TuitionFee = {
  "Faculty of Science & Information Technology": [
    {
      program_name: "B.Sc. in Computer Science and Engineering (CSE)",
      majors:
        "Artificial Intelligence, Software Development, Network and Communication, Algorithms, Embedded Systems and Robotics",
      credit_hours: 154.5,
      duration: "4 Years",
      payable_during_admission: 61750,
      average_semester_fees: 85000,
      tuition_fees: 782250,
      total_program_fees: 1020450,
    },
    {
      program_name: "B.Sc. in Software Engineering (SWE)",
      majors: "General, Cyber Security, Data Science, Robotics",
      credit_hours: 147,
      duration: "4 Years",
      payable_during_admission: 61750,
      average_semester_fees: 78000,
      tuition_fees: 709500,
      total_program_fees: 952500,
    },
    {
      program_name: "B.Sc. in Multimedia & Creative Technology (MCT)",
      majors: "3D Animation & VFX, Visual Arts, Game Design, Film and Media",
      credit_hours: 147,
      duration: "4 Years",
      payable_during_admission: 59550,
      average_semester_fees: 60000,
      tuition_fees: 508950,
      total_program_fees: 744150,
    },
  ],
  "Faculty of Business & Entrepreneurship": [
    {
      program_name: "Bachelor of Business Administration (BBA)",
      majors:
        "Finance, Marketing, Accounting, HRM, MIS, Supply Chain, Entrepreneurship",
      credit_hours: 130,
      duration: "4 Years",
      payable_during_admission: 65910,
      average_semester_fees: 65000,
      tuition_fees: 574675,
      total_program_fees: 789575,
    },
    {
      program_name: "Bachelor of Tourism & Hospitality Management (BTHM)",
      majors: "Hospitality Management",
      credit_hours: 130,
      duration: "4 Years",
      payable_during_admission: 64350,
      average_semester_fees: 56000,
      tuition_fees: 459600,
      total_program_fees: 698600,
    },
  ],
  "Faculty of Health & Life Sciences": [
    {
      program_name: "Bachelor of Pharmacy (B. Pharm)",
      credit_hours: 160,
      duration: "4 Years",
      payable_during_admission: 66000,
      average_semester_fees: 122500,
      tuition_fees: 752200,
      total_program_fees: 1008200,
    },
    {
      program_name: "B.Sc. in Nutrition and Food Engineering (NFE)",
      credit_hours: 151,
      duration: "4 Years",
      payable_during_admission: 53450,
      average_semester_fees: 75000,
      tuition_fees: 408750,
      total_program_fees: 620450,
    },
  ],
  "Graduate Programs": [
    {
      program_name: "M.Sc. in Computer Science and Engineering (CSE)",
      credit_hours: "42 - 63",
      duration: "1.5 - 2 Years",
      payable_during_admission: 28750,
      average_semester_fees: 40000,
      tuition_fees: "99000 - 162000",
      total_program_fees: "173500 - 249000",
    },
    {
      program_name: "Master of Business Administration (MBA)",
      majors: "24 Majors Available",
      credit_hours: "40 - 69",
      duration: "1 - 2 Years",
      payable_during_admission: 30250,
      average_semester_fees: 55000,
      tuition_fees: "131400 - 219000",
      total_program_fees: "189025 - 315000",
    },
  ],
  "Faculty of Engineering": [
    {
      program_name: "Bachelor of Architecture (B.Arch)",
      majors: "Architectural Design, Urban Planning, Landscape Architecture",
      credit_hours: 185,
      duration: "5 Years",
      payable_during_admission: 75500,
      average_semester_fees: 95000,
      tuition_fees: 950000,
      total_program_fees: 1250500,
    },
  ],
  "Faculty of Humanities & Social Sciences": [
    {
      program_name: "LL.B (Hons)",
      majors: "Corporate Law, Criminal Law, International Law",
      credit_hours: 138,
      duration: "4 Years",
      payable_during_admission: 62500,
      average_semester_fees: 68000,
      tuition_fees: 650000,
      total_program_fees: 850000,
    },
    {
      program_name: "B.A. in English Literature & Language",
      majors: "Literature, Linguistics, Creative Writing",
      credit_hours: 124,
      duration: "4 Years",
      payable_during_admission: 48500,
      average_semester_fees: 45000,
      tuition_fees: 420000,
      total_program_fees: 520000,
    },
    {
      program_name: "BSS in Journalism, Media and Communication",
      majors: "Digital Journalism, Broadcast, PR & Advertising",
      credit_hours: 130,
      duration: "4 Years",
      payable_during_admission: 55000,
      average_semester_fees: 52000,
      tuition_fees: 510000,
      total_program_fees: 650000,
    },
    {
      program_name: "BSS in Economics",
      majors: "Development Economics, Finance, Econometrics",
      credit_hours: 128,
      duration: "4 Years",
      payable_during_admission: 50000,
      average_semester_fees: 48000,
      tuition_fees: 485000,
      total_program_fees: 580000,
    },
    {
      program_name: "BSS in Sociology",
      majors: "Social Development, Urban Sociology, Research Methodology",
      credit_hours: 120,
      duration: "4 Years",
      payable_during_admission: 45000,
      average_semester_fees: 42000,
      tuition_fees: 380000,
      total_program_fees: 495000,
    },
  ],
};

